---
- name: Test that image server VM is ready
  hosts: k3s
  gather_facts: false
  tasks:
    - name: Wait for VM
      ansible.builtin.wait_for_connection:
        timeout: 60

- name: Provision nodes
  hosts: k3s
  become: true
  gather_facts: true
  roles:
    - role: provision

- name: Install k3s leader
  hosts: leader
  become: true
  roles:
    - role: k3s
    - role: calico
    - role: metallb
      vars:
        metallb_addresses:
          - name: api-server
            ip: "{{ cluster_api_vip }}"
          - name: ingress
            ip: "{{ cluster_ingress_vip }}"
    - role: endpoint_copier
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Install k3s on followers and workers
  hosts: follower,worker
  become: true
  roles:
    - role: k3s

- name: OpenISCSI install
  hosts: k3s
  become: true
  roles:
    - role: openiscsi

- name: Fetch kubeconfig
  hosts: leader
  gather_facts: false
  become: true
  tasks:
    - name: Fetch kubeconfig
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ kubeconfig_path }}"
        flat: true

- name: Modify kubeconfig file
  hosts: localhost
  connection: local
  tasks:
    - name: Replace IP in kubeconfig
      ansible.builtin.lineinfile:
        path: "{{ kubeconfig_path }}"
        regexp: "server:"
        line: "    server: https://{{ cluster_api_vip }}:6443"
        state: present
