---
- name: Fetch kubeconfig
  hosts: leader
  gather_facts: false
  become: true
  tasks:
    - name: Wait for VM
      ansible.builtin.wait_for_connection:
        timeout: 120

    - name: Check that the kubeconfig exists
      stat:
        path: /etc/rancher/k3s/k3s.yaml
      register: kubeconfig_result
      until: kubeconfig_result.stat.exists
      retries: 50
      delay: 5

    - name: Fetch kubeconfig
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ kubeconfig_path }}"
        flat: true

- name: Modify kubeconfig file
  hosts: localhost
  connection: local
  tasks:
    - name: Replace IP in kubeconfig
      ansible.builtin.lineinfile:
        path: "{{ kubeconfig_path }}"
        regexp: "server:"
        line: "    server: https://{{ cluster_vip }}:6443"
        state: present
